require("bigchess")
require("stringi")
require("stringr")
require("tm")
require("dplyr")
require("tidytext")
require("tidyverse")
require("tidygraph")
require("dplyr")
require("markovchain")
require("diagram")
require("ggplot2")
require("ggraph")
require("gganimate")
require("networkD3")

